excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://brehon.io
title: Brehon Arbitration
tagline: A third party arbitration protocol for smart contracts
description: A third party arbitration protocol for smart contracts
paginate: 5
