excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://brehon.io
title: Brehon Arbitration Protocol
tagline: A third party arbitration protocol for smart contracts
description: A third party arbitration protocol for smart contracts
paginate: 5
